baseURL: "https://cboy.space/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: cboy's space
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-FBRMT4K2N7

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 10
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archives
                  url: archives
                  weight: 5
                - name: Tags
                  url: tags/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "everything about cboy"
    author: cboy

    comments: true
    giscus:
        repo: "yuhangbin/yuhangbin.github.io"
        repoID: "MDEwOlJlcG9zaXRvcnkyODMzODc5NDc"
        category: "General"
        categoryID: "DIC_kwDOEOQoK84CWyvp"
        mapping: "pathname"
        reactionsEnabled: "1"
        emitMetadata: "0"
        inputPosition: "bottom"
        theme: "light"
        lang: "zh-CN"

    defaultTheme: light
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true

    homeInfoParams:
        Title: Hello!
        Content: Welcome to cboy's space
    socialIcons:
        - name: Github
          url: "https://github.com/yuhangbin"
        - name: Twitter
          url: "https://twitter.com/yuhangbin"
        - name: Discord
          url: "https://discord.gg/FKTykR3Z"
        - name: Rss
          url: "index.xml"

    # editPost:
    #     URL: "https://github.com/yuhangbin"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    profileMode:
        enabled: false
        title: "Space for cboy" # optional default will be site title
        subtitle: ""
        imageUrl: "https://avatars.githubusercontent.com/u/17566866?v=4" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Github
              url: "https://github.com/yuhangbin"
            - name: Twitter
              url: "https://twitter.com/yuhangbin"
            - name: Discord
              url: "https://discord.gg/FKTykR3Z"
