baseURL: "https://yuhangbin.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: cboy's space
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 10
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archives
                  url: archives
                  weight: 5
                - name: Tags
                  url: tags/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "everything about cboy"
    author: cboy
    # author: ["Me", "You"] # multiple authors

    defaultTheme: light

    profileMode:
        enabled: true
        title: "Space for CharlieYu" # optional default will be site title
        subtitle: "Everything will be fine."
        imageUrl: "https://avatars.githubusercontent.com/u/17566866?v=4" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Github
              url: "https://github.com/yuhangbin"
            - name: Twitter
              url: "https://twitter.com/yuhangbin"
            - name: Bilibili
              url: "https://www.bilibili.com/"
